baseURL = "https://sslarch.github.io/"
theme = "risotto"
title = "CAA/SSLA"
author = "CAA SSLA"
copyright = ""
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params.theme]
palette = "caa-ssla"
mode = "dark-mode"

[params.about]
title = "Scientific Scripting Languages in Archaeology"
description = "A special interest group of [CAA International](https://caa-international.org/) dedicated to scientific scripting languages in archaeology."
logo_image = "images/sig_ssla_logo.svg"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Mailing list"
url = "https://groups.google.com/forum/#!forum/scientific-scripting-languages-in-archaeology"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub organisation"
url = "https://github.com/sslarch"

[[params.socialLinks]]
icon = "fab fa-twitter"
title = "Tweet @caa_ssla"
url = "https://twitter.com/caa_ssla"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
